-- 1. For migration purposes

DROP TABLE IF EXISTS dispensation_items      CASCADE;
DROP TABLE IF EXISTS dispensations          CASCADE;
DROP TABLE IF EXISTS prescription_items     CASCADE;
DROP TABLE IF EXISTS prescriptions          CASCADE;
DROP TABLE IF EXISTS prescriptions_statuses CASCADE;

DROP TABLE IF EXISTS sale_items             CASCADE;
DROP TABLE IF EXISTS payments               CASCADE;

DROP TABLE IF EXISTS price_list_items       CASCADE;
DROP TABLE IF EXISTS inventory_batches      CASCADE;
DROP TABLE IF EXISTS drug_manufacturers     CASCADE;
DROP TABLE IF EXISTS drugs                  CASCADE;
DROP TABLE IF EXISTS drug_forms             CASCADE;
DROP TABLE IF EXISTS drug_categories        CASCADE;
DROP TABLE IF EXISTS manufacturers          CASCADE;

DROP TABLE IF EXISTS insurance_claims          CASCADE;
DROP TABLE IF EXISTS patient_insurance         CASCADE;
DROP TABLE IF EXISTS insurance_plans           CASCADE;
DROP TABLE IF EXISTS insurance_claim_statuses  CASCADE;
DROP TABLE IF EXISTS insurance_companies       CASCADE;

DROP TABLE IF EXISTS sales                 CASCADE;

DROP TABLE IF EXISTS patients              CASCADE;

DROP TABLE IF EXISTS user_roles            CASCADE;
DROP TABLE IF EXISTS role_permissions      CASCADE;
DROP TABLE IF EXISTS users                 CASCADE;

DROP TABLE IF EXISTS storage_areas         CASCADE;
DROP TABLE IF EXISTS temperature_ranges    CASCADE;

DROP TABLE IF EXISTS branches              CASCADE;
DROP TABLE IF EXISTS branch_types          CASCADE;

DROP TABLE IF EXISTS payment_methods       CASCADE;
DROP TABLE IF EXISTS sale_types            CASCADE;

DROP TABLE IF EXISTS doctors               CASCADE;

DROP TABLE IF EXISTS roles                 CASCADE;
DROP TABLE IF EXISTS permissions           CASCADE;

DROP TABLE IF EXISTS receipt_items          CASCADE;
DROP TABLE IF EXISTS receipts               CASCADE;
DROP TABLE IF EXISTS purchase_order_items   CASCADE;
DROP TABLE IF EXISTS purchase_orders        CASCADE;
DROP TABLE IF EXISTS purchase_order_statuses CASCADE;
DROP TABLE IF EXISTS suppliers              CASCADE;

DROP TABLE IF EXISTS stock_count_items      CASCADE;
DROP TABLE IF EXISTS stock_counts           CASCADE;
DROP TABLE IF EXISTS stock_adjustments      CASCADE;
DROP TABLE IF EXISTS stock_adjustment_reasons CASCADE;
DROP TABLE IF EXISTS stock_transactions     CASCADE;
DROP TABLE IF EXISTS transaction_types      CASCADE;

-- 2. Master tables

CREATE TABLE insurance_companies (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    phone       VARCHAR(20)  NOT NULL,
    email       VARCHAR(100),
    address     VARCHAR(255),
    CONSTRAINT uq_insurance_companies_name UNIQUE (name)
);

CREATE TABLE insurance_claim_statuses (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status      VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE branch_types (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE permissions (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_permissions_code UNIQUE (code)
);

CREATE TABLE roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE drug_categories (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(80)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_drug_categories_name UNIQUE (name)
);

CREATE TABLE drug_forms (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_drug_forms_name UNIQUE (name)
);

CREATE TABLE manufacturers (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(150) NOT NULL,
    country VARCHAR(80),
    phone   VARCHAR(20),
    email   VARCHAR(100),
    CONSTRAINT uq_manufacturers_name UNIQUE (name)
);

CREATE TABLE temperature_ranges (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    range       VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE payment_methods (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method      VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_payment_methods_method UNIQUE (method)
);

CREATE TABLE sale_types (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_sale_types_type UNIQUE (type)
);

CREATE TABLE doctors (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(50)  NOT NULL,
    last_name      VARCHAR(50)  NOT NULL,
    license_number VARCHAR(50)  NOT NULL,
    specialty      VARCHAR(80)  NOT NULL,
    phone          VARCHAR(20)  NOT NULL,
    email          VARCHAR(100),
    CONSTRAINT uq_doctors_license_number UNIQUE (license_number)
);

CREATE TABLE prescriptions_statuses (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status      VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE suppliers (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(150) NOT NULL,
    phone   VARCHAR(20)  NOT NULL,
    email   VARCHAR(100),
    address VARCHAR(255),
    CONSTRAINT uq_suppliers_name UNIQUE (name)
);

CREATE TABLE purchase_order_statuses (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status      VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE transaction_types (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE stock_adjustment_reasons (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason      VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

-- 3. Dependable tables

CREATE TABLE role_permissions (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id) REFERENCES permissions (id),
    CONSTRAINT uq_role_permissions UNIQUE (role_id, permission_id)
);


CREATE TABLE branches (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    type_id     INTEGER      NOT NULL,
    phone       VARCHAR(20),
    email       VARCHAR(100),
    address     VARCHAR(150) NOT NULL,
    CONSTRAINT fk_branches_type
        FOREIGN KEY (type_id) REFERENCES branch_types (id)
);

CREATE TABLE storage_areas (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id            INTEGER      NOT NULL,
    area_name            VARCHAR(100) NOT NULL,
    temperature_range_id INTEGER      NOT NULL,
    CONSTRAINT fk_storage_areas_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_storage_areas_temperature_range
        FOREIGN KEY (temperature_range_id) REFERENCES temperature_ranges (id)
);


CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id     INTEGER      NOT NULL,
    first_name    VARCHAR(50)  NOT NULL,
    last_name     VARCHAR(50)  NOT NULL,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT fk_users_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id)
);

CREATE TABLE user_roles (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT uq_user_roles UNIQUE (user_id, role_id)
);


CREATE TABLE patients (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        VARCHAR(50)  NOT NULL,
    last_name         VARCHAR(50)  NOT NULL,
    date_of_birth     DATE         NOT NULL,
    gender            VARCHAR(10)  NOT NULL,
    phone             VARCHAR(20)  NOT NULL,
    address           VARCHAR(255) NOT NULL,
    primary_branch_id INTEGER      NOT NULL,
    CONSTRAINT fk_patients_primary_branch
        FOREIGN KEY (primary_branch_id) REFERENCES branches (id)
);


CREATE TABLE prescriptions (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id        INTEGER      NOT NULL,
    doctor_id         INTEGER      NOT NULL,
    branch_id         INTEGER      NOT NULL,
    prescription_date DATE         NOT NULL,
    status_id         INTEGER      NOT NULL,
    notes             VARCHAR(255),
    CONSTRAINT fk_prescriptions_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_prescriptions_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT fk_prescriptions_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_prescriptions_status
        FOREIGN KEY (status_id) REFERENCES prescriptions_statuses (id)
);


CREATE TABLE sales (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    INTEGER   NOT NULL,
    patient_id   INTEGER   NOT NULL,
    sold_by      INTEGER   NOT NULL,     
    sale_date    TIMESTAMP NOT NULL,
    sale_type_id INTEGER   NOT NULL,
    CONSTRAINT fk_sales_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_sales_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_sales_sold_by
        FOREIGN KEY (sold_by) REFERENCES users (id),
    CONSTRAINT fk_sales_sale_type
        FOREIGN KEY (sale_type_id) REFERENCES sale_types (id)
);


CREATE TABLE insurance_plans (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insurance_company_id INTEGER      NOT NULL,
    plan_name            VARCHAR(100) NOT NULL,
    coverage_pct         DECIMAL(5, 2) NOT NULL,
    CONSTRAINT fk_insurance_plans_company
        FOREIGN KEY (insurance_company_id)
        REFERENCES insurance_companies (id)
);

CREATE TABLE patient_insurance (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id        INTEGER      NOT NULL,
    insurance_plan_id INTEGER      NOT NULL,
    member_number     VARCHAR(50)  NOT NULL,
    valid_from        DATE         NOT NULL,
    valid_to          DATE,
    CONSTRAINT fk_patient_insurance_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_patient_insurance_plan
        FOREIGN KEY (insurance_plan_id) REFERENCES insurance_plans (id)
);

CREATE TABLE insurance_claims (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id           INTEGER NOT NULL,
    insurance_plan_id INTEGER NOT NULL,
    claim_date        DATE    NOT NULL,
    status_id         INTEGER NOT NULL,
    CONSTRAINT fk_insurance_claims_sale
        FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_insurance_claims_plan
        FOREIGN KEY (insurance_plan_id) REFERENCES insurance_plans (id),
    CONSTRAINT fk_insurance_claims_status
        FOREIGN KEY (status_id) REFERENCES insurance_claim_statuses (id)
);


CREATE TABLE drugs (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(150) NOT NULL,
    generic_name      VARCHAR(150) NOT NULL,
    category_id       INTEGER      NOT NULL,
    form_id           INTEGER      NOT NULL,
    strength          VARCHAR(50)  NOT NULL,
    is_controlled     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_refrigerated   BOOLEAN      NOT NULL DEFAULT FALSE,
    default_pack_size INTEGER,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_drugs_category
        FOREIGN KEY (category_id) REFERENCES drug_categories (id),
    CONSTRAINT fk_drugs_form
        FOREIGN KEY (form_id) REFERENCES drug_forms (id)
);

CREATE TABLE inventory_batches (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_id         INTEGER      NOT NULL,
    storage_area_id INTEGER      NOT NULL,
    batch_number    VARCHAR(50)  NOT NULL,
    expiry_date     DATE         NOT NULL,
    initial_qty     INTEGER      NOT NULL,
    unit_cost       DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_inventory_batches_drug
        FOREIGN KEY (drug_id) REFERENCES drugs (id),
    CONSTRAINT fk_inventory_batches_storage_area
        FOREIGN KEY (storage_area_id) REFERENCES storage_areas (id)
);

CREATE TABLE drug_manufacturers (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_id         INTEGER NOT NULL,
    manufacturer_id INTEGER NOT NULL,
    product_code    VARCHAR(50),
    CONSTRAINT fk_drug_manufacturers_drug
        FOREIGN KEY (drug_id) REFERENCES drugs (id),
    CONSTRAINT fk_drug_manufacturers_manufacturer
        FOREIGN KEY (manufacturer_id) REFERENCES manufacturers (id)
);


CREATE TABLE price_list_items (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_id         INTEGER       NOT NULL,
    unit_price      DECIMAL(10,2) NOT NULL,
    discount_amount DECIMAL(4,3)  NOT NULL,
    start_date      TIMESTAMP     NOT NULL,
    end_date        TIMESTAMP,
    CONSTRAINT fk_price_list_items_drug
        FOREIGN KEY (drug_id) REFERENCES drugs (id)
);


CREATE TABLE prescription_items (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id     INTEGER      NOT NULL,
    drug_id             INTEGER      NOT NULL,
    dosage              VARCHAR(50)  NOT NULL,
    frequency           VARCHAR(50)  NOT NULL,
    duration_days       INTEGER      NOT NULL,
    quantity_prescribed INTEGER      NOT NULL,
    CONSTRAINT fk_prescription_items_prescription
        FOREIGN KEY (prescription_id) REFERENCES prescriptions (id),
    CONSTRAINT fk_prescription_items_drug
        FOREIGN KEY (drug_id) REFERENCES drugs (id)
);

CREATE TABLE dispensations (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id INTEGER   NOT NULL,
    dispensed_by    INTEGER   NOT NULL,     
    dispense_date   TIMESTAMP NOT NULL,
    CONSTRAINT fk_dispensations_prescription
        FOREIGN KEY (prescription_id) REFERENCES prescriptions (id),
    CONSTRAINT fk_dispensations_user
        FOREIGN KEY (dispensed_by) REFERENCES users (id)
);

CREATE TABLE dispensation_items (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispensation_id    INTEGER  NOT NULL,
    batch_id           INTEGER  NOT NULL,
    quantity_dispensed INTEGER  NOT NULL,
    CONSTRAINT fk_dispensation_items_dispensation
        FOREIGN KEY (dispensation_id) REFERENCES dispensations (id),
    CONSTRAINT fk_dispensation_items_batch
        FOREIGN KEY (batch_id) REFERENCES inventory_batches (id)
);


CREATE TABLE sale_items (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id   INTEGER NOT NULL,
    price_id  INTEGER NOT NULL,
    quantity  INTEGER NOT NULL,
    batch_id  INTEGER NOT NULL,
    CONSTRAINT fk_sale_items_sale
        FOREIGN KEY (sale_id)  REFERENCES sales (id),
    CONSTRAINT fk_sale_items_price
        FOREIGN KEY (price_id) REFERENCES price_list_items (id),
    CONSTRAINT fk_sale_items_batch
        FOREIGN KEY (batch_id) REFERENCES inventory_batches (id)
);

CREATE TABLE payments (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id          INTEGER       NOT NULL,
    payment_date     TIMESTAMP     NOT NULL,
    amount           DECIMAL(10,2) NOT NULL,
    payment_method_id INTEGER      NOT NULL,
    CONSTRAINT fk_payments_sale
        FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_payments_method
        FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)
);


CREATE TABLE purchase_orders (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   INTEGER NOT NULL,
    supplier_id INTEGER NOT NULL,
    created_by  INTEGER NOT NULL,   
    order_date  DATE    NOT NULL,
    status_id   INTEGER NOT NULL,
    CONSTRAINT fk_purchase_orders_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_purchase_orders_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_purchase_orders_created_by
        FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_purchase_orders_status
        FOREIGN KEY (status_id) REFERENCES purchase_order_statuses (id)
);

CREATE TABLE purchase_order_items (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id INTEGER       NOT NULL,
    drug_id           INTEGER       NOT NULL,
    ordered_qty       INTEGER       NOT NULL,
    expected_unit_cost DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_purchase_order_items_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id),
    CONSTRAINT fk_purchase_order_items_drug
        FOREIGN KEY (drug_id) REFERENCES drugs (id)
);

CREATE TABLE receipts (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id  INTEGER      NOT NULL,
    received_by        INTEGER      NOT NULL,   
    supplier_invoice_no VARCHAR(50) NOT NULL,
    CONSTRAINT uq_receipts_supplier_invoice UNIQUE (supplier_invoice_no),
    CONSTRAINT fk_receipts_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id),
    CONSTRAINT fk_receipts_received_by
        FOREIGN KEY (received_by) REFERENCES users (id)
);

CREATE TABLE receipt_items (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id  INTEGER       NOT NULL,
    drug_id     INTEGER       NOT NULL,
    received_qty INTEGER      NOT NULL,
    unit_cost   DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_receipt_items_receipt
        FOREIGN KEY (receipt_id) REFERENCES receipts (id),
    CONSTRAINT fk_receipt_items_drug
        FOREIGN KEY (drug_id) REFERENCES drugs (id)
);


CREATE TABLE stock_counts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id  INTEGER      NOT NULL,
    count_date DATE         NOT NULL,
    counted_by INTEGER      NOT NULL,    
    remarks    VARCHAR(255),
    CONSTRAINT fk_stock_counts_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_stock_counts_counted_by
        FOREIGN KEY (counted_by) REFERENCES users (id)
);

CREATE TABLE stock_count_items (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_count_id INTEGER NOT NULL,
    batch_id      INTEGER NOT NULL,
    system_qty    INTEGER NOT NULL,
    counted_qty   INTEGER NOT NULL,
    CONSTRAINT fk_stock_count_items_count
        FOREIGN KEY (stock_count_id) REFERENCES stock_counts (id),
    CONSTRAINT fk_stock_count_items_batch
        FOREIGN KEY (batch_id) REFERENCES inventory_batches (id)
);

CREATE TABLE stock_transactions (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id           INTEGER   NOT NULL,
    branch_id          INTEGER   NOT NULL,
    transaction_type_id INTEGER  NOT NULL,
    quantity_change    INTEGER   NOT NULL,
    transaction_date   TIMESTAMP NOT NULL,
    performed_by       INTEGER   NOT NULL,   
    remarks            VARCHAR(255),
    CONSTRAINT fk_stock_transactions_batch
        FOREIGN KEY (batch_id) REFERENCES inventory_batches (id),
    CONSTRAINT fk_stock_transactions_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_stock_transactions_type
        FOREIGN KEY (transaction_type_id) REFERENCES transaction_types (id),
    CONSTRAINT fk_stock_transactions_performed_by
        FOREIGN KEY (performed_by) REFERENCES users (id)
);

CREATE TABLE stock_adjustments (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id        INTEGER   NOT NULL,
    old_qty         INTEGER   NOT NULL,
    new_qty         INTEGER   NOT NULL,
    reason_id       INTEGER   NOT NULL,
    adjustment_date TIMESTAMP NOT NULL,
    approved_by     INTEGER   NOT NULL,   
    CONSTRAINT fk_stock_adjustments_batch
        FOREIGN KEY (batch_id) REFERENCES inventory_batches (id),
    CONSTRAINT fk_stock_adjustments_reason
        FOREIGN KEY (reason_id) REFERENCES stock_adjustment_reasons (id),
    CONSTRAINT fk_stock_adjustments_approved_by
        FOREIGN KEY (approved_by) REFERENCES users (id)
);
